const words = [
    "CRIME BOSS ROCKAY CITY", "HALO WARS DEFINITIVE EDITION Ex", "HALO WARS 2 ULTIMATE EDITION Ex", "CYBERPUNK 2077","MARVEL'S SPIDER-MAN MILES MORALES","ASSASSIN'S CREED II DELUXE EDITION","ALAN WAKE II DELUXE EDITION",
    "CALL OF DUTY BLACK OPS II PLUTONIUM","JUST CAUSE 4 COMPLETE EDITION","ASSASSIN'S CREED ODYSSEY GOLD EDITION","BATMAN ARKHAM KNIGHT PREMIUM EDITION","MAFIA DEFINITIVE EDITION","MAFIA 2 DEFINITIVE EDITION",
    "WOLFENSTEIN II THE NEW COLOSSUS","WATCH DOGS 2 DELUXE EDITION","TOM CLANCY'S GHOST RECON WILDLANDS GOLD EDITION","FAR CRY 6 GOLD EDITION","OUTPOST INFINITY SIEGE VANGUARD EDITION","DYING LIGHT 2 STAY HUMAN",
    "MARVEL SPIDER-MAN 2 DELUXE EDITION","DEAD SPACE 2","ROBOCOP ROGUE CITY","ASSASSIN'S CREED VALHALLA","SEKIRO SHADOWS DIE TWICE GAME OF THE YEAR","WANTED DEAD","GENERATION ZERO ULTIMATE BUNDLE","MORTAL KOMBAT XL",
    "SHADOW OF THE TOMB RAIDER DEFINITIVE EDITION","CONTROL ULTIMATE EDITION","RATCHET AND CLANK RIFT APART","NEED FOR SPEED HEAT DELUXE EDITION","DAYMARE 1994 SANDCASTLE","LEGO HORIZON ADVENTURES DELUXE EDITION",
    "EURO TRUCK SIMULATOR 2","ASSASSIN'S CREED ORIGINS GOLD EDITION","DAYS GONE","MASS EFFECT LEGENDARY EDITION","SNOWRUNNER","BLACK SAILS","HITMAN ABSOLUTION PROFESSIONAL EDITION","RAGE 2 DELUXE EDITION",
    "CRYSIS 3 REMASTERED Ex","Gears of War 4 Ex","Gears of war Ex","BIOSHOCK INFINITE","Prey","KINGDOM HEARTS III + RE MIND","LIES OF P DELUXE EDITION","OUTCAST A NEW BEGINNING","BRIGHT MEMORY: INFINITE","HIGH ON LIFE","BATTLEFIELD 3",
    "BANISHERS GHOSTS OF NEW EDEN","REMNANT II ULTIMATE EDITION","BATTLEFIELD 1 ULTIMATE EDITION","CALL OF DUTY MODERN WARFARE 2 REMASTERED","CALL OF DUTY BLACK OPS III","FLINTLOCK THE SIEGE OF DAWN","RAYMAN ORIGINS","FAR CRY 3",
    "NECROMUNDA HIRED GUN","STEELRISING","THE LAST OF US PART I","GHOSTBUSTERS: THE VIDEO GAME REMASTERIZADO","EVIL WEST","AIRPORTSIM","PSYCHONAUTS 2","EMPIRE OF THE ANTS DELUXE","A QUIET PLACE THE ROAD AHEAD",
    "SOULSTICE","FORSPOKEN DIGITAL DELUXE EDITION","RESISTANCE 3","CONTAIN","POWERWASH ADVENTURE","WARFRAME","WOLFENSTEIN THE NEW ORDER","OUTPOST INFINITY SIEGE VANGUARD","GENERATION ZERO ULTIMATE BUNDLE",
    "STAR WARS JEDI SURVIVOR","BRIGHT MEMORY INFINITE","RETURNAL","CALL OF DUTY GHOSTS","TITANFALL 2","HALF-LIFE ALYX","CALL OF DUTY MODERN WARFARE REMASTERED","STRAY – GAMESFULL","EVERSPACE 2","GOD OF WAR RAGNARÖK",
    "MECHWARRIOR 5 MERCENARIES","SHADOW WARRIOR 3","WOLFENSTEIN YOUNGBLOOD","STAR WARS JEDI FALLEN ORDER","DRAGON BALL SPARKING! ZERO","NEED FOR SPEED MOST WANTED LIMITED EDITION Ex","UNCHARTED 4 LEGACY THIEVES COLLECTION",
    "FAR CRY NEW DAWN DELUXE EDITION","PACIFIC DRIVE","UNKNOWN 9 AWAKENING","WARHAMMER 40000 SPACE MARINE 2","QUANTUM BREAK STEAM EDITION","CALL OF DUTY WWII","METAL GEAR SOLID V THE PHANTOM PAIN",
    "TERMINATOR RESISTANCE","SCARS ABOVE","OBSERVER SYSTEM REDUX","CRASH BANDICOOT 4 IT'S ABOUT TIME","CRYSIS 2 REMASTERED","GHOST OF TSUSHIMA DIRECTOR'S CUT","GEARS 5 ULTIMATE EDITION","THE EVIL WITHIN 2","HOMEFRONT THE REVOLUTION",
    "ORI AND THE WILL OF THE WISPS","MECHWARRIOR 5: CLANS - TRIALS OF WAR","INDIANA JONES AND THE GREAT CIRCLE","SYNDICATE 2012","UNRAVEL TWO","BATTLEFIELD 4","CALL OF DUTY BLACK OPS","ASSASSINS CREED MIRAGE MASTER ASSASSIN EDITION",
    "CHERNOBYLITE COMPLETE EDITION"

];


//HOGWARTS LEGACY

let usedWords = []; // Lista para palabras usadas
let remainingWords = [...words]; // Copia del array original

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

function updateProgressBar() {
    const progressBar = document.getElementById('progress-bar');
    const progressPercentage = (usedWords.length / words.length) * 100;
    progressBar.style.width = `${progressPercentage}%`;
}

function updateWordCount() {
    const remainingCount = document.getElementById('remaining-count');
    remainingCount.textContent = remainingWords.length;
}

function getRandomColor() {
    const colors = ['#0f0', '#f00', '#00f', '#ff0'];
    return colors[Math.floor(Math.random() * colors.length)];
}

function showRandomWord() {
    if (remainingWords.length === 0) {
        alert('Todas las palabras han sido mostradas. Reiniciando...');
        remainingWords = [...words];
        usedWords = [];
    }
    shuffleArray(remainingWords);
    const randomWord = remainingWords.pop();
    usedWords.push(randomWord);

    const wordElement = document.getElementById('random-word');
    wordElement.textContent = randomWord;

    const leftButtons = document.querySelectorAll('#left-dpad div');
    const rightButtons = document.querySelectorAll('#right-buttons div');
    leftButtons.forEach(button => (button.style.background = getRandomColor()));
    rightButtons.forEach(button => (button.style.background = getRandomColor()));

    updateWordCount();
    updateProgressBar();
}

document.addEventListener('DOMContentLoaded', () => updateWordCount());
//www.compucalitv.com
